spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

supabase:
  s3:
    endpoint: ${SUPABASE_ENDPOINT}
    region: ${SUPABASE_REGION}
    access-key: ${SUPABASE_ACCESS_KEY}
    secret-key: ${SUPABASE_SECRET_KEY}
    bucket-name: ${SUPABASE_BUCKET}